### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by imaekgames** [IlgarLunin/UE4OVRLipSyncCookFrameSequence#1]
`context.ProcessFrame(PCMData + offs, ChunkSizeSamples, Visemes, LaughterScore, NumChannels > 1);`

Line 55 in CookFrameSequenceAsync.cpp shows error while compiling,
void UOVRLipSyncContextWrapper::ProcessFrame(const int16_t *,int,TArray<float,FDefaultAllocator> &,float &,int32_t &,bool)': cannot convert argument 5 from 'bool' to 'int32_t &

**Comment by IlgarLunin** [comment]
@imaekgames what is your engine version?
